version: '3'

services:
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - "1515:15"

  database_auction:
    image: postgres:${POSTGRES_VERSION:-14}-alpine
    container_name: database_auction
    environment:
      POSTGRES_DB: ${POSTGRES_AUCTION_DB:-auction_service}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
      POSTGRES_USER: ${POSTGRES_USER:-app}
    command: postgres -c 'max_connections=250'

  database_authentication:
    image: postgres:${POSTGRES_VERSION:-14}-alpine
    container_name: database_authentication
    environment:
      POSTGRES_DB: ${POSTGRES_AUTH_DB:-authentiaction_service}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
      POSTGRES_USER: ${POSTGRES_USER:-app}
    command: postgres -c 'max_connections=250'

  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - '8080:80'
    volumes:
      - .:/var/www/OnlineAuction
      - ./Build/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - microservice_auction
      - microservice_authentication

  redis:
    image: redis:7.0.5-alpine3.16
    container_name: redis
    ports:
      - '6380:6380'
    environment:
      - ALLOW_EMPTY_PASSWORD=true

  amqp:
    image: rabbitmq:3.11.0-management-alpine
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      AMQP_URL: 'amqp://rabbitmq?connection_attempts=5&retry_delay=5'
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER:-guest}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS:-pass}
    logging:
      driver: none

  microservice_authentication:
    container_name: microservice_authentication
    build:
      context: ./AuthenticationService/Docker
    volumes:
      - ./AuthenticationService:/var/www/OnlineAuction/AuthenticationService:rw
      - ./AuthenticationService/Docker/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf
    depends_on:
      - database_authentication
      - amqp

  microservice_auction:
    container_name: microservice_auction
    build:
      context: ./AuctionService/Docker
    volumes:
      - ./AuctionService:/var/www/OnlineAuction/AuctionService:rw
      - ./AuctionService/Docker/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf
    command: php-fpm
    depends_on:
      - database_auction
      - amqp
